CREATE TABLE zadaniya (
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
zadanie VARCHAR(100) NOT NULL,
project VARCHAR(255) NOT NULL,
data VARCHAR(255) NOT NULL,
comment VARCHAR(255) NOT NULL,
price INT(10) NOT NULL
)
